### ISSUE TITLE
Effects for individual .play() calls?

### ISSUE THREAD

**Issue by bbottema** [alexanderwallin/howler-plugin-effect-chain#1]
If I look at your example, it looks like Howler is globally configured with the chorus effect. Is it possible to use your plugin on individual playbacks?

**Comment by alexanderwallin** [comment]
Ouph, good question. This was a while ago, but I'd say probably not. Not without amendments, anyway. This plugin just injects an effect chain before `Howler`'s master gain.

**Comment by bbottema** [comment]
Ok, that's really too bad. I'm looking for a way to add existing effect libraries to Howler.js

**Comment by alexanderwallin** [comment]
Sorry, mate. Perhaps there is another library more suitable?
